window.BIMS_CONFIG = {
  SUPABASE_URL: 'https://wqddzkhnmrgfusbjfori.supabase.co',
  SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxZGR6a2hubXJnZnVzYmpmb3JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAyNjI5MDksImV4cCI6MjEwNTgzODkwOX0.B0RKBKZouGOs9_C3soYfJWBP1WQdrrW_6Q4Z5jACvlk'
};

